name: FLAG Research lab
url: http://flaglab.github.io

exclude: [bibble, README.md, Makefile]

# colorize code snippets with the pygments module
highlighter: rouge

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
  - key: labhead
    name: Principal Investigators
  - key: postdoc
    name: Post-docs
  - key: predoc
    name: Doctoral Students
  - key: ugrad
    name: Students
  - key: alumni
    name: Alumni
  - key: collab
    name: Collaborators

# Sections on the "collaborators" page.
collab_types:
  - key: university
    name: University
  - key: researcher
    name: Researchers

# Number of news stories on the front page.
front_page_news: 0

# Base pathname for links.
base: ''

# make pages for the _projects folder
collections:
  projects:
    output: true
  researchareas:
    output: true
  thesistopics:
    output: true
  bib:
    output: true

# Navigation bar links.
navigation:
  - title: Home
    link: /index.html
  #- title: Research Areas
  #  link: /research-areas.html
  - title: Publications
    link: /publications.html
  - title: Members
    link: /members.html  
  - title: Collaborators
    link: /collaborators.html
  - title: Artifacts
    link: /artifacts.html
  - title: Thesis topics
    link: /thesis.html
